package lazy.dev.dynamo.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@DynamoDBTable(tableName = "users")
@Data public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String firstName;
    private String lastName;
}
